/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haolb_client_utils_SecureUtil */

#ifndef _Included_com_haolb_client_utils_SecureUtil
#define _Included_com_haolb_client_utils_SecureUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haolb_client_utils_SecureUtil
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_haolb_client_utils_SecureUtil_encode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_haolb_client_utils_SecureUtil
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_haolb_client_utils_SecureUtil_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
